[project]
include_dirs = [
    "src/aide_scolarite",
    "src/commun",
    "src/commun/structures"
]
build_dir    = "_build"    # Définit où sortir les fichiers compilés générés.
target_dir   = "_target"   # Définit où sortir les fichiers finaux des cibles.

# Chaque section [[target]] décrit une cible de construction pour le projet

[[target]]
name     = "prestagri_catala"
modules  = [ "Quotient_familial", "Aide_scolarite"]
tests    = [ "tests/commun", "tests/aide_scolarite" ]
backends = [ "python" ]
